// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package api

import (
	"time"
)

const (
	AccessCodeScopes = "accessCode.Scopes"
)

// Defines values for DonationAsset.
const (
	DonationAssetEth  DonationAsset = "eth"
	DonationAssetUsdc DonationAsset = "usdc"
	DonationAssetUsdt DonationAsset = "usdt"
)

// Defines values for DonationStatus.
const (
	Confirmed   DonationStatus = "confirmed"
	Failed      DonationStatus = "failed"
	Unconfirmed DonationStatus = "unconfirmed"
)

// Defines values for DonationStatsStatus.
const (
	Closed DonationStatsStatus = "closed"
	Open   DonationStatsStatus = "open"
	Paused DonationStatsStatus = "paused"
)

// Defines values for PriceAsset.
const (
	PriceAssetEth   PriceAsset = "eth"
	PriceAssetTruth PriceAsset = "truth"
)

// Defines values for UserStatsStatus.
const (
	None      UserStatsStatus = "none"
	Staking   UserStatsStatus = "staking"
	Unstaking UserStatsStatus = "unstaking"
)

// AffiliateRequest defines model for affiliate_request.
type AffiliateRequest struct {
	// Code affiliate code for the donation in question
	Code string `json:"code"`

	// TxHash transaction hash for the donation in question
	TxHash string `json:"tx_hash"`
}

// Donation defines model for donation.
type Donation struct {
	// Amount amount donated
	Amount string `json:"amount"`

	// Asset asset donated
	Asset DonationAsset `json:"asset"`

	// Price token price at the time of donation
	Price string `json:"price"`

	// Status ethereum blockchain status of the donation
	Status DonationStatus `json:"status"`

	// Tokens amount of tokens corresponding to the donated amount
	Tokens string    `json:"tokens"`
	Ts     time.Time `json:"ts"`

	// TxHash transaction hash for the donation in question
	TxHash string `json:"tx_hash"`

	// UsdAmount optional USD amount, omitted in case of USD stable coins
	UsdAmount *string `json:"usd_amount,omitempty"`
}

// DonationAsset asset donated
type DonationAsset string

// DonationStatus ethereum blockchain status of the donation
type DonationStatus string

// DonationData defines model for donation_data.
type DonationData struct {
	// Prices an array of prices
	Prices []Price       `json:"prices"`
	Stats  DonationStats `json:"stats"`
}

// DonationStats defines model for donation_stats.
type DonationStats struct {
	Status DonationStatsStatus `json:"status"`

	// Tokens number of tokens claimable by donors
	Tokens string `json:"tokens"`

	// Total total funds raised in USD
	Total string `json:"total"`
}

// DonationStatsStatus defines model for DonationStats.Status.
type DonationStatsStatus string

// Error defines model for error.
type Error struct {
	// Code error code
	Code int `json:"code"`

	// Message error message
	Message string `json:"message"`
}

// Price defines model for price.
type Price struct {
	Asset PriceAsset `json:"asset"`

	// Price asset price in USD
	Price string    `json:"price"`
	Ts    time.Time `json:"ts"`
}

// PriceAsset defines model for Price.Asset.
type PriceAsset string

// UserData defines model for user_data.
type UserData struct {
	// Donations an array of donations
	Donations []Donation `json:"donations"`
	Stats     UserStats  `json:"stats"`
}

// UserStats defines model for user_stats.
type UserStats struct {
	// Reward staking rewards the user is eligible to claim
	Reward string `json:"reward"`

	// Staked number of tokens the user staked; must be <= `tokens`
	Staked string          `json:"staked"`
	Status UserStatsStatus `json:"status"`

	// Tokens number of tokens the user is eligible to claim
	Tokens string `json:"tokens"`

	// Total total funds donated by this address in USD
	Total string `json:"total"`

	// Ts date/time at which the staking status was last modified
	Ts *time.Time `json:"ts,omitempty"`
}

// UserStatsStatus defines model for UserStats.Status.
type UserStatsStatus string

// SetAffiliateCodeJSONRequestBody defines body for SetAffiliateCode for application/json ContentType.
type SetAffiliateCodeJSONRequestBody = AffiliateRequest
